FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./

RUN npm ci

COPY src ./src
COPY tsconfig.json ./

RUN npx prisma generate

CMD ["npx", "tsx", "src/cli/index.ts"]
