# Generated by Django 6.0.5 on 2026-05-22 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MantecatoUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mantecato_user',
            },
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('event_data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('website_event_id', models.UUIDField()),
                ('data_key', models.CharField(max_length=500)),
                ('string_value', models.CharField(blank=True, max_length=500, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('date_value', models.DateTimeField(blank=True, null=True)),
                ('data_type', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_data',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('website_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('revenue', models.DecimalField(decimal_places=10, max_digits=30)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'revenue',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('name_filters', models.JSONField()),
                ('modifier', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'segment',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('browser', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('screen', models.CharField(blank=True, max_length=11, null=True)),
                ('language', models.CharField(blank=True, max_length=35, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('distinct_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('session_data_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('data_key', models.CharField(max_length=500)),
                ('string_value', models.CharField(blank=True, max_length=500, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('date_value', models.DateTimeField(blank=True, null=True)),
                ('data_type', models.IntegerField()),
                ('distinct_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session_data',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('access_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('team_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(default='member', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team_user',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=500, null=True)),
                ('share_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('team_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('visit_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_path', models.CharField(max_length=500)),
                ('url_query', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer_path', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer_query', models.CharField(blank=True, max_length=500, null=True)),
                ('referrer_domain', models.CharField(blank=True, max_length=500, null=True)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('event_type', models.IntegerField(default=1)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=20, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('screen', models.CharField(blank=True, max_length=11, null=True)),
                ('language', models.CharField(blank=True, max_length=35, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=50, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=50, null=True)),
                ('gclid', models.CharField(blank=True, max_length=100, null=True)),
                ('fbclid', models.CharField(blank=True, max_length=100, null=True)),
                ('msclkid', models.CharField(blank=True, max_length=100, null=True)),
                ('ttclid', models.CharField(blank=True, max_length=100, null=True)),
                ('twclid', models.CharField(blank=True, max_length=100, null=True)),
                ('li_fat_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'website_event',
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.report',),
        ),
    ]
