# Generated by Django 6.0.5 on 2026-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_timestamp_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('mantecato-dashboard', 'Dashboard'), ('mantecato-saved-view', 'Saved view'), ('mantecato-annotation', 'Annotation'), ('api-key', 'API key'), ('mantecato-bot-config', 'Bot detection config'), ('mantecato-scheduled-export', 'Scheduled export')], max_length=100),
        ),
    ]
