# Generated by Django 6.0.5 on 2026-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventdata',
            index=models.Index(fields=['website_event_id'], name='idx_ed_website_event_id'),
        ),
        migrations.AddIndex(
            model_name='eventdata',
            index=models.Index(fields=['website_id', 'created_at'], name='idx_ed_website_created'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['country', 'device'], name='idx_session_country_device'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['website_id'], name='idx_session_website_id'),
        ),
        migrations.AddIndex(
            model_name='sessiondata',
            index=models.Index(fields=['session_id'], name='idx_sd_session_id'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['website_id', 'created_at', 'event_type'], name='idx_we_website_created_type'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['session_id'], name='idx_we_session_id'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(fields=['visit_id'], name='idx_we_visit_id'),
        ),
    ]
