# Generated by Django 6.0.5 on 2026-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_analytics_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user_id', 'type'], name='idx_report_user_type'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['website_id', 'type'], name='idx_report_website_type'),
        ),
    ]
