# Generated by Django 6.0.5 on 2026-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_report_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['website_id', '-created_at'], name='idx_rev_website_created'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['website_id', 'session_id'], name='idx_rev_session'),
        ),
        migrations.AddIndex(
            model_name='sessiondata',
            index=models.Index(fields=['website_id'], name='idx_sd_website_id'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 1)), fields=['website_id', '-created_at'], include=('visit_id', 'session_id', 'url_path'), name='idx_we_pageview_hot'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 2)), fields=['website_id', '-created_at', 'event_name'], name='idx_we_event_hot'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 1)), fields=['visit_id', 'created_at'], name='idx_we_visit_created_pv'),
        ),
    ]
