# Generated by Django 6.0.5 on 2026-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perf_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='SavedView',
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('mantecato-dashboard', 'Dashboard'), ('api-key', 'API key'), ('mantecato-bot-config', 'Bot detection config'), ('mantecato-scheduled-export', 'Scheduled export')], max_length=100),
        ),
    ]
