# Generated by Django 6.0.5 on 2026-06-05 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_annotation_delete_savedview_alter_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmamiImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('target_website_id', models.UUIDField()),
                ('source_website_id', models.UUIDField()),
                ('since', models.DateField(blank=True, null=True)),
                ('replace', models.BooleanField(default=False)),
                ('current_table', models.CharField(blank=True, max_length=50, null=True)),
                ('total_rows', models.BigIntegerField(default=0)),
                ('imported_rows', models.BigIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'umami_import_job',
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='idx_uij_user_created')],
            },
        ),
    ]
