# Generated by Django 6.0.5 on 2026-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_umamiimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantecatouser',
            name='password_is_default',
            field=models.BooleanField(default=False),
        ),
    ]
