# Generated by Django 6.0.5 on 2026-06-07 22:12

import apps.core.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_region_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSketch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('bucket_start', models.DateTimeField()),
                ('scope', models.CharField(default='site', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', max_length=500)),
                ('registers', models.BinaryField(default=apps.core.models._visitor_sketch_registers)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visitor_sketch',
            },
        ),
        migrations.AddField(
            model_name='websiteevent',
            name='bot_reason',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='websiteevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websiteevent',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 1)), fields=['website_id', '-created_at'], include=('url_path', 'is_bot'), name='idx_we_pageview_hot'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 1)), fields=['website_id', 'is_bot', '-created_at'], name='idx_we_bot_hot'),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 2)), fields=['website_id', 'event_name', '-created_at'], name='idx_we_event_name_hot'),
        ),
        migrations.AddIndex(
            model_name='visitorsketch',
            index=models.Index(fields=['website_id', 'scope', 'bucket_start'], name='idx_vs_site_scope_bucket'),
        ),
        migrations.AddConstraint(
            model_name='visitorsketch',
            constraint=models.UniqueConstraint(fields=('website_id', 'bucket_start', 'scope', 'scope_value'), name='uniq_visitor_sketch_bucket_scope'),
        ),
    ]
