# Generated by Django 6.0.5 on 2026-06-08 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitorsketch_remove_websiteevent_idx_we_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('day', models.DateField()),
                ('scope', models.CharField(default='site', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', max_length=500)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('bounces', models.IntegerField(default=0)),
                ('total_pageviews', models.IntegerField(default=0)),
                ('total_duration_s', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visitor_daily',
            },
        ),
        migrations.CreateModel(
            name='VisitorDaySalt',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('salt', models.BinaryField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visitor_day_salt',
            },
        ),
        migrations.CreateModel(
            name='VisitorDayState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('day', models.DateField()),
                ('visitor_key', models.CharField(max_length=64)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('visits', models.IntegerField(default=1)),
                ('bounces', models.IntegerField(default=0)),
                ('cur_visit_pageviews', models.IntegerField(default=1)),
                ('cur_visit_duration_s', models.IntegerField(default=0)),
                ('total_pageviews', models.IntegerField(default=1)),
                ('total_duration_s', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'visitor_day_state',
            },
        ),
        migrations.RemoveIndex(
            model_name='visitorsketch',
            name='idx_vs_site_scope_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='visitorsketch',
            name='uniq_visitor_sketch_bucket_scope',
        ),
        migrations.DeleteModel(
            name='VisitorSketch',
        ),
        migrations.AddIndex(
            model_name='visitordaily',
            index=models.Index(fields=['website_id', 'scope', 'day'], name='idx_vd_site_scope_day'),
        ),
        migrations.AddConstraint(
            model_name='visitordaily',
            constraint=models.UniqueConstraint(fields=('website_id', 'day', 'scope', 'scope_value'), name='uniq_visitor_daily_scope'),
        ),
        migrations.AddIndex(
            model_name='visitordaystate',
            index=models.Index(fields=['website_id', 'day'], name='idx_vds_site_day'),
        ),
        migrations.AddIndex(
            model_name='visitordaystate',
            index=models.Index(fields=['day'], name='idx_vds_day'),
        ),
        migrations.AddConstraint(
            model_name='visitordaystate',
            constraint=models.UniqueConstraint(fields=('website_id', 'day', 'visitor_key'), name='uniq_visitor_day_key'),
        ),
    ]
