# Generated by Django 6.0.5 on 2026-06-08 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visitordaily_visitordaysalt_visitordaystate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('period_start', models.DateField()),
                ('scope', models.CharField(default='site', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', max_length=500)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('bounces', models.IntegerField(default=0)),
                ('total_pageviews', models.IntegerField(default=0)),
                ('total_duration_s', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visitor_period',
            },
        ),
        migrations.CreateModel(
            name='VisitorSalt',
            fields=[
                ('period', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('salt', models.BinaryField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visitor_salt',
            },
        ),
        migrations.CreateModel(
            name='VisitorScopeState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField()),
                ('period', models.CharField(max_length=16)),
                ('scope', models.CharField(max_length=20)),
                ('scope_value', models.CharField(max_length=500)),
                ('visitor_key', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'visitor_scope_state',
            },
        ),
        migrations.DeleteModel(
            name='VisitorDaySalt',
        ),
        migrations.RemoveIndex(
            model_name='visitordaystate',
            name='idx_vds_day',
        ),
        migrations.AddField(
            model_name='visitordaystate',
            name='entry_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitordaystate',
            name='period',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='visitordaystate',
            index=models.Index(fields=['website_id', 'period'], name='idx_vds_site_period'),
        ),
        migrations.AddIndex(
            model_name='visitordaystate',
            index=models.Index(fields=['period'], name='idx_vds_period'),
        ),
        migrations.AddIndex(
            model_name='visitorperiod',
            index=models.Index(fields=['website_id', 'scope', 'period_start'], name='idx_vp_site_scope_period'),
        ),
        migrations.AddConstraint(
            model_name='visitorperiod',
            constraint=models.UniqueConstraint(fields=('website_id', 'period_start', 'scope', 'scope_value'), name='uniq_visitor_period_scope'),
        ),
        migrations.AddIndex(
            model_name='visitorscopestate',
            index=models.Index(fields=['website_id', 'period', 'scope'], name='idx_vss_site_period_scope'),
        ),
        migrations.AddIndex(
            model_name='visitorscopestate',
            index=models.Index(fields=['period'], name='idx_vss_period'),
        ),
        migrations.AddConstraint(
            model_name='visitorscopestate',
            constraint=models.UniqueConstraint(fields=('website_id', 'period', 'scope', 'scope_value', 'visitor_key'), name='uniq_visitor_scope_key'),
        ),
    ]
