# Generated by Django 6.0.5 on 2026-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_websiteevent_visitor_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordaystate',
            name='cur_page_engaged_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='websiteevent',
            name='referrer_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('event_type', 1)), fields=['website_id', 'referrer_domain', '-created_at'], name='idx_we_referrer_hot'),
        ),
    ]
