# Generated by Django 6.0.5 on 2026-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_visitordaystate_cur_page_engaged_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitordaily',
            name='bot_bounces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitordaily',
            name='bot_total_duration_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitordaily',
            name='bot_total_pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitordaily',
            name='bot_unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitordaily',
            name='bot_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorperiod',
            name='bot_bounces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorperiod',
            name='bot_total_duration_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorperiod',
            name='bot_total_pageviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorperiod',
            name='bot_unique_visitors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitorperiod',
            name='bot_visits',
            field=models.IntegerField(default=0),
        ),
    ]
