# Generated by Django 6.0.5 on 2026-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_websiteevent_idx_we_visitor_key_pv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteevent',
            name='is_bot',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
