# Generated by Django 6.0.5 on 2026-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_websiteevent_is_bot'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='websiteevent',
            index=models.Index(condition=models.Q(('visitor_key__isnull', False)), fields=['created_at'], name='idx_we_visitor_key_expiry'),
        ),
    ]
