# Generated by Django 6.0.5 on 2026-06-26 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_websiteevent_idx_we_visitor_key_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_id', models.UUIDField(unique=True)),
                ('count', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'badge_hit',
            },
        ),
    ]
