# Generated by Django 6.0.5 on 2026-10-01 14:04

import authlib.oauth2.rfc6749.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('redirect_uris', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='AIConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_method', models.CharField(choices=[('oauth', 'OAuth'), ('personal', 'Token')], max_length=16)),
                ('scopes', models.JSONField(default=list)),
                ('website_ids', models.JSONField(default=list)),
                ('authorized_scopes', models.JSONField(default=list)),
                ('authorized_websites', models.JSONField(default=list)),
                ('auth_fingerprint', models.CharField(max_length=64)),
                ('notice_version', models.CharField(max_length=40)),
                ('notice_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_connections.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_connections.aiconnection')),
            ],
        ),
        migrations.CreateModel(
            name='AIActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=48)),
                ('outcome', models.CharField(max_length=32)),
                ('website_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_connections.aiconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at', '-id'], name='ai_connecti_user_id_283085_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiconnection',
            index=models.Index(fields=['user', '-created_at', '-id'], name='ai_connecti_user_id_4e6bee_idx'),
        ),
    ]
