# Generated by Django 6.0.5 on 2026-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aiconnection',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='aiconnection',
            name='revoked_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
