# Generated by Django 6.0.5 on 2026-10-02 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_connections', '0002_alter_aiactivity_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconnection',
            name='auth_method',
            field=models.CharField(choices=[('oauth', 'OAuth connector'), ('personal', 'Personal token')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aiconnection',
            name='expires_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='oauthcredential',
            name='expires_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='aiconnection',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', False), ('auth_method', 'personal'), _connector='OR'), name='ai_conn_expiry_or_personal'),
        ),
        migrations.AddConstraint(
            model_name='oauthcredential',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', False), models.Q(('connection__isnull', False), ('kind', 'personal')), _connector='OR'), name='ai_cred_expiry_or_personal'),
        ),
    ]
